# Generated by Django 3.2.12 on 2024-10-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie_article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriearticle',
            name='taux_tva',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
