# Generated by Django 5.1.3 on 2024-12-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_compte_client_matricule_fiscal_client_ville_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
