# Generated by Django 3.2.12 on 2024-10-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='total_remise',
        ),
    ]
