# Generated by Django 3.2.12 on 2024-10-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_auto_20241012_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorieArticle',
        ),
    ]
