# Generated by Django 3.2.12 on 2024-10-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_delete_categoriearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taux_tva', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
            ],
        ),
    ]
