# Generated by Django 3.2.12 on 2024-10-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0005_categoriearticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorieArticle',
        ),
    ]
