# Generated by Django 3.2.12 on 2024-11-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0008_alter_facture_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', to='facture.facture'),
        ),
    ]
