# Generated by Django 5.1.3 on 2024-12-08 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0009_alter_lignefacture_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
