# Generated by Django 3.2.12 on 2024-10-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tva', '0001_initial'),
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVA_Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total_tva', models.DecimalField(decimal_places=3, max_digits=10)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.facture')),
                ('taux_tva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tva.tva')),
            ],
        ),
    ]
