# Generated by Django 3.2.12 on 2024-10-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_tva', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
