# Generated by Django 3.2.12 on 2024-11-13 21:24

from django.db import migrations, models
from datetime import datetime

def set_default_created_at(apps, schema_editor):
    Article = apps.get_model('article', 'Article')
    default_date = datetime(2024, 1, 1)  # Set a default date for existing rows

    for article in Article.objects.all():
        if not article.created_at:
            article.created_at = default_date
            article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        # Add the new created_at field to the Article model
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        # Run a function to populate existing rows with a default timestamp
        migrations.RunPython(set_default_created_at),
    ]
