# Generated by Django 5.1.3 on 2024-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20241113_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
