# Generated by Django 5.1.3 on 2024-12-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
