# Generated by Django 3.2.12 on 2024-11-13 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0002_auto_20241113_2124'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devis', models.CharField(max_length=100)),
                ('date_devis', models.DateField(default=django.utils.timezone.now)),
                ('total_ht', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_tva', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('etat', models.CharField(choices=[('impayee', 'Impayée'), ('payee', 'Payée')], default='impayée', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('taux_remise', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('montant_remise', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10)),
                ('montant_tva', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis')),
            ],
        ),
    ]
