# Generated by Django 3.2.12 on 2024-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_alter_lignedevis_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='etat',
            field=models.CharField(choices=[('non_valide', 'Non Validé'), ('valide', 'Validé')], default='non_valide', max_length=20),
        ),
    ]
