# Generated by Django 5.1.3 on 2024-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_alter_devis_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
